[package]
name = "par-acquit-de"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.1.6"
indexmap = "1.9.1"
rand = "0.8.5"
rocket = "0.5.0-rc.2"
serde = { version = "1", features = ["derive"] }
